name: HandLink
description: "Sign Language Recognition App"
version: 1.0.0+1
publish_to: 'none'
homepage: https://github.com/MohamedBadour/HandLink

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.1.0
  dio: ^5.3.4
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^7.1.2
  linkedin_login: ^3.1.3
  jwt_decoder: ^2.0.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.2
  google_generative_ai: ^0.4.3
  image_picker: ^1.0.4
  cached_network_image: ^3.3.1
  flutter_tts: ^4.2.3
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  lottie: ^3.3.1
  font_awesome_flutter: ^10.6.0
  logger: ^2.0.2+1
  url_launcher: ^6.2.1
  intl: 0.20.2
  path_provider: ^2.1.1
  path: ^1.8.3
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/google_icon.png
    - assets/facebook_icon.png
    - assets/linkedin_icon.png
    - assets/animations/
    - assets/icons/